### DISCUSSION TITLE
项目初始化

### DISCUSSION THREAD

**Discussion by lencx** [lencx/rust-fe#6] [Blog]
> [lencx/rust-fe](https://github.com/lencx/rust-fe) - GitHub 仓库（内含代码）。如果文章对您有所帮助，欢迎分享或 Star 此项目，您的支持是我创作的最大动力，感恩！

示例代码：[examples/hello](https://github.com/lencx/rust-fe/tree/main/examples/hello)

### npm

前端使用 npm 来初始化项目，生成 `package.json`：

```bash
# -y 静默生成，跳过询问
$ npm init -y
```

`package.json` 包含以下字段，更多字段请参考 [npm configuring - package.json](https://docs.npmjs.com/cli/configuring-npm/package-json)：

```json
{
  "name": "hello",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

### cargo

Rust 使用 cargo 命令来初始化项目，生成 `Cargo.toml` 和 `src/main.rs` 文件（默认）：

```bash
# 默认：二进制（应用程序）模板
# cargo new --bin hello
$ cargo new hello

hello
├── Cargo.toml # 与 package.json 类似
└── src # 源代码
    └── main.rs # 应用入口
```

如果使用 `--lib` 则生成 `src/lib.rs` 文件：

```bash
# 库模板
$ cargo new --lib hello

hello
├── Cargo.toml
└── src
    └── lib.rs
```

Cargo.toml 与 package.json 中的大部分字段具有类似性，更多字段请参考 [The Manifest Format](https://doc.rust-lang.org/cargo/reference/manifest.html)：

```toml
# 基本信息
[package]
# 包名称只能使用字母、数字、- 或 _，并且不能为空
name = "hello"
# 包版本
version = "0.1.0"
# 包描述
description = "hello world"
# 包作者
authors = ["Alice <a@example.com>", "Bob <b@example.com>"]
# 关键词
keywords = []
# 指定 Rust 版本（目前有 2015，2018 和 2021）
# https://doc.rust-lang.org/edition-guide/introduction.html
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 依赖
[dependencies]
serde = "1.0.147"

# 特定平台下的依赖 (windows)，cfg 支持 not, any 和 all
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
[target.'cfg(windows)'.dependencies]
winhttp = "0.4.0"

# 特定平台下的依赖 (x86)
[target.'cfg(target_arch = "x86")'.dependencies]
native-i686 = { path = "native/i686" }

# 开发依赖，与 dependencies 类似
[dev-dependencies]
```

### 安装依赖

在前端可以使用 `npm install [dep]` 来安装依赖，在 Rust 中也有类似的命令。但 cargo 本身并不支持，所以需要先安装 [cargo-edit](https://github.com/killercup/cargo-edit) 插件来支持：

```bash
$ cargo install cargo-edit
```

安装完成后 cargo 将支持这些子命令：`add`、`rm`、`upgrade` 和 `set-version`。例如 `cargo add serde`。

## 运行

在前端会使用 `npm`、`yarn` 或 `pnpm` 来管理项目，安装依赖的过程中都会针对 package.json 的依赖生成 lock 文件（`package-lock.json`、`yarn.lock` 或 `pnpm-lock.yaml`），而 `cargo` 也类似，会生成 `Cargo.lock`。

第一次启动项目，如果有未安装的依赖，cargo 会自动下载，下载完成后编译并执行：

```bash
$ cargo run
   Compiling hello v0.1.0 (/Users/lencx/rust-fe/examples/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 1.12s
     Running `target/debug/hello`
Hello, world!
```

## 测试

前往 `src/main.rs` 添加测试代码：

```rs
fn main() {
    println!("Hello, world!");
}

// 这里先简单了解，后面会陆续写文章讲解
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
}
```

```bash
$ cargo test
   Compiling hello v0.1.0 (/Users/lencx/rust-fe/examples/hello)
    Finished test [unoptimized + debuginfo] target(s) in 3.08s
     Running unittests src/main.rs (target/debug/deps/hello-138fb452958b6b71)

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

## 构建

```bash
$ cargo build

# 生产模式：更长的编译时间，会对代码进行优化（用编译时间换程序性能的提升）
$ cargo build --release
```

默认情况下，执行以下命令，均处于 debug 模式，生成的产物位于 `target/debug` 目录下：

- `cargo run` - 运行包
- `cargo build` - 构建包
- `cargo test` - 执行包内的所有单元和集成测试
- `cargo check` - 检查本地包及其所有依赖项是否有错误。编译包但不执行代码生成，比运行 `cargo build` 更快（项目越大越明显）

但是均可以在后面添加 `--release` 参数来切换模式，如 `cargo build --release`，生成的产物位于 `target/release` 目录下。

## 发布

与 npm 将包发布到 [npmjs](https://www.npmjs.com) 类似，执行以下命令，会将程序包发布到 [crates.io](https://crates.io) 来进行托管：

```bash
$ cargo publish
```
